source 'https://github.com/CocoaPods/Specs.git'
		platform :ios, '7.0'
		inhibit_all_warnings!

			target ‘ZhongFaZhiZao’ do
   			  pod 'SDWebImage'
              pod 'JSONModel'
              pod 'Masonry'
              pod 'AFNetworking'
              pod 'FMDB'
              pod 'MJRefresh'
              pod 'QRCodeReaderViewController'
            
              
              pod 'RongCloudIM/IMLib', '~> 2.8.3'
              pod 'RongCloudIM/IMKit', '~> 2.8.3'
              pod 'JPush'
              
              # 友盟基础库
              # 友盟统计
              pod 'UMCAnalytics'
              # U-Share SDK UI模块（分享面板，建议添加）
              pod 'UMCShare/UI'
              # 集成QQ/QZone/TIM(完整版7.6M)
              pod 'UMCShare/Social/QQ'
              # 集成微信(完整版14.4M)
              pod 'UMCShare/Social/WeChat'
              # 集成新浪微博(完整版25.3M)
              pod 'UMCShare/Social/Sina'
              # 集成短信
              pod 'UMCShare/Social/SMS'
              
end
